### ISSUE TITLE
Access violation, read at FFFFFFFF

### ISSUE THREAD

**Issue by blauergrashalm** [zusitools/zusi_linux_installer#1]
Nach der Auswahl der zu installierenden Komponenten erhalte ich die angezeigte Fehlermeldung. selbiges passiert auch wenn man dein Skript nicht verwendet, habe in winecfg sowohl windows 7 und XP ausprobiert.
![image](https://user-images.githubusercontent.com/16773676/215152109-bdd861d8-b658-414e-b0ff-d2e061137084.png)

**Comment by zusitools** [comment]
Kann ich reproduzieren. Bitte mal mit dem neuesten Release (https://github.com/zusitools/zusi_linux_installer/releases/download/v0.4/zusi_linux_installer.tar.gz) ausprobieren.

**Comment by blauergrashalm** [comment]
Hammer wie schnell du das hinbekommen hast, damit klappts nun! Danke sehr :)
